# Generated by Django 3.2.16 on 2022-10-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
